spring:
  application:
    name: wms
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sleepwalker?serverTimezone=GMT%2B8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      client-id: wms
      client-secret: wms123
      access-token-uri: http://localhost:18090/oauth2_resource_server/oauth/token
      user-authorization-uri: http://localhost:18090/oauth2_resource_server/oauth/authorize
    resource:
      user-info-uri: http://localhost:18090/oauth2_resource_server/user/me

logging:
  level:
    root: debug

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://master:18080/eureka

server:
  port: 18070
  servlet:
    context-path: /wms

mybatis:
  type-aliases-package: com.example.wms.mapper
  mapper-locations: classpath:mappers/*.xml