spring:
  application:
    name: oauth2_resource_server
  datasource:
    url: jdbc:mysql://localhost:3306/sleepwalker?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    cache: false

server:
  port: 18090
  servlet:
    context-path: /oauth2_resource_server

eureka:
  instance:
    hostname: master
  client:
    service-url:
      defaultZone: http://master:18080/eureka

logging:
  level:
    root: debug